[build]
  command = "npm run build"
  publish = "dist"

# Set headers to improve caching and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Single Page Application routing (Fallback for React handling if you ever add React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200